In [ ]:
%matplotlib inline

import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
a=np.arange(10).reshape(1,2,5)
a=torch.tensor(a)

In [3]:
#shape of a tensor
print(a.size())
print(a.shape)
print(a.reshape(1,5,2).shape)

torch.Size([1, 2, 5])
torch.Size([1, 2, 5])
torch.Size([1, 5, 2])


In [4]:
#creating tensors from numpy arrays
arr=np.arange(30).reshape(10,3)

a1=torch.tensor(arr)
print(a1)

a2=torch.from_numpy(arr)
print(a2)

a3=torch.Tensor(arr)
print(a3) #this one will assign float dtype to the array elements

a4=torch.as_tensor(arr)
print(a4)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]], dtype=torch.int32)
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]], dtype=torch.int32)
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.],
        [27., 28., 29.]])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]], dtype=torch.int32)


In [5]:
#default dtype
torch.get_default_dtype()

torch.float32

In [6]:
#specifying the type we want
a_new=torch.tensor(arr,dtype=torch.float16)
a_new

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.],
        [27., 28., 29.]], dtype=torch.float16)

In [7]:
#total elements in a tensor
print(a_new.numel())
print(torch.tensor(a_new.shape).prod())

30
tensor(30)


In [8]:
#squeeze and unsqueeze -->squeeze removes the dimensions that have values 1 while unsqueeze adds one more dimension

data=np.arange(5).reshape(1,5,1)
deep_tensor=torch.tensor(data)
print(deep_tensor.shape)
print(deep_tensor.squeeze(dim=2).shape)
print(deep_tensor.squeeze(dim=2).unsqueeze(dim=1).shape)

torch.Size([1, 5, 1])
torch.Size([1, 5])
torch.Size([1, 1, 5])


In [9]:
#flatten a tensor
def flatten(arr):
    arr=arr.reshape(1,-1)
    arr=arr.squeeze(dim=0)
    return arr

res=flatten(torch.tensor(data))
print(res)
print(res.shape)

temp=torch.tensor(data)
print(temp.reshape(temp.numel()).shape)
print(temp.reshape(-1).shape)


tensor([0, 1, 2, 3, 4], dtype=torch.int32)
torch.Size([5])
torch.Size([5])
torch.Size([5])


In [10]:
print(temp.shape)
print(temp.flatten(start_dim=0).shape)
print(temp.flatten(start_dim=1).shape)
print(temp.flatten(start_dim=2).shape)

torch.Size([1, 5, 1])
torch.Size([5])
torch.Size([1, 5])
torch.Size([1, 5, 1])


In [11]:
print(torch.is_tensor(temp))
print(torch.is_storage(temp))

True
False


In [12]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [13]:
torch.eye(4,2)

tensor([[1., 0.],
        [0., 1.],
        [0., 0.],
        [0., 0.]])

In [14]:
b=torch.linspace(2,20,10,requires_grad=True)
print(b,b.requires_grad)

tensor([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.], requires_grad=True) True


In [15]:
print(torch.is_tensor(b))
print(torch.is_storage(b))

True
False


In [16]:
torch.logspace(10,20,10) #logarithmic space tensors in the range [math.pow(10,10),math.pow(20,10)]

tensor([1.0000e+10, 1.2915e+11, 1.6681e+12, 2.1544e+13, 2.7826e+14, 3.5938e+15,
        4.6416e+16, 5.9949e+17, 7.7426e+18, 1.0000e+20])

In [17]:
#random numbers from uniform dist b?w 0 and 1
print(torch.rand(1))
print(torch.rand(5))

tensor([0.2319])
tensor([0.1793, 0.2498, 0.1280, 0.6038, 0.7299])


In [18]:
torch.rand(2,3) #uniform random numbers creating a matrix of shape 2*3

tensor([[0.6012, 0.9200, 0.1685],
        [0.8967, 0.9449, 0.4186]])

In [19]:
torch.randn(2) #normal distribution with mean=0 & stddev=1

tensor([ 0.4914, -0.3416])

In [20]:
print(torch.randperm(10)) #here  10 is the range upto which we will generate all the numbers from 0 to 9 randomly it is same as

arr=list(range(10))
import random
random.shuffle(arr)
torch.from_numpy(np.array(arr))

tensor([1, 0, 2, 3, 9, 4, 7, 5, 8, 6])


tensor([7, 0, 5, 8, 6, 1, 9, 4, 2, 3], dtype=torch.int32)

In [21]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
torch.arange(1,15)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
torch.arange(2,20,2)

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
a1=torch.randperm(50).reshape(2,25)

In [25]:
#returns the indices of the maximum values of a tensor across a dimension.
#if dim is None,the argmax of the flattened input is returned.
print(torch.argmax(a1)) 

tensor(37)


In [26]:
from IPython.display import display
display(a1)
display(torch.argmax(a1,dim=0)) #across rows
display(torch.argmax(a1,dim=1)) #across columns

tensor([[37, 28, 44, 41, 20, 18, 30, 46,  8,  7, 15, 25, 19, 23, 31, 11, 40, 48,
          2,  9, 38, 14,  1, 21, 12],
        [10, 13, 42, 34,  5, 16, 17, 36, 35,  6,  4,  3, 49,  0, 26, 43, 33, 45,
         39, 32, 29, 27, 22, 47, 24]])

tensor([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
        1])

tensor([17, 12])

In [27]:
max_element,indices=torch.max(a1,dim=1)
print(max_element,indices)

tensor([48, 49]) tensor([17, 12])


In [28]:
display(torch.argmin(a1,dim=0)) #across rows
display(torch.argmin(a1,dim=1)) #across columns
min_element,min_indices=torch.min(a1,dim=1)
print(min_element,min_indices)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
        0])

tensor([22, 13])

tensor([1, 0]) tensor([22, 13])


In [29]:
x=torch.arange(20).reshape(4,5)
x

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [30]:
y=torch.arange(20,40).reshape(4,5)
y

tensor([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]])

In [31]:
torch.cat((x,y),dim=0)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]])

In [32]:
torch.cat((x,y),dim=1)

tensor([[ 0,  1,  2,  3,  4, 20, 21, 22, 23, 24],
        [ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
        [10, 11, 12, 13, 14, 30, 31, 32, 33, 34],
        [15, 16, 17, 18, 19, 35, 36, 37, 38, 39]])

In [33]:
torch.add(x,y)

tensor([[20, 22, 24, 26, 28],
        [30, 32, 34, 36, 38],
        [40, 42, 44, 46, 48],
        [50, 52, 54, 56, 58]])

In [34]:
torch.sub(x,y)

tensor([[-20, -20, -20, -20, -20],
        [-20, -20, -20, -20, -20],
        [-20, -20, -20, -20, -20],
        [-20, -20, -20, -20, -20]])

In [35]:
torch.mul(x,y)

tensor([[  0,  21,  44,  69,  96],
        [125, 156, 189, 224, 261],
        [300, 341, 384, 429, 476],
        [525, 576, 629, 684, 741]])

In [36]:
torch.matmul(x,y.reshape(5,4))

tensor([[ 320,  330,  340,  350],
        [1020, 1055, 1090, 1125],
        [1720, 1780, 1840, 1900],
        [2420, 2505, 2590, 2675]])

In [37]:
a,b=torch.chunk(x.reshape(5,4),chunks=2,dim=0)

In [38]:
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [39]:
b

tensor([[12, 13, 14, 15],
        [16, 17, 18, 19]])

In [40]:
a,b=torch.chunk(x.reshape(5,4),chunks=2,dim=1)
a

tensor([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17]])

In [41]:
b

tensor([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19]])

In [42]:
a=torch.arange(27).reshape(9,3)
b=torch.arange(27,54).reshape(9,3)

In [43]:
c=torch.where(a>15,a,b)

In [44]:
c #where the conditions is false elements from b are picked up else element from a  are pciked

tensor([[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]])

In [45]:
#The gather function collects elements from a tensor and places it in another tensor using an index argument. 
#The index position is determined by the LongTensor function .
torch.gather(c,dim=1,index=torch.LongTensor([[0,1],[1,2],[1,1],[2,1],[1,2],[1,1],[0,1],[0,1],[1,1]]))

tensor([[27, 28],
        [31, 32],
        [34, 34],
        [38, 37],
        [40, 41],
        [16, 16],
        [18, 19],
        [21, 22],
        [25, 25]])

In [46]:
torch.gather(c,dim=0,index=torch.LongTensor([[0,1,2]]))

tensor([[27, 31, 35]])

In [47]:
c=c.reshape(1,-1,3)
torch.gather(c,dim=1,index=torch.LongTensor([[[0,1,2]]]))

tensor([[[27, 31, 35]]])

In [48]:
c=c.squeeze()
c

tensor([[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]])

In [49]:
indices=torch.LongTensor([1,2])

In [50]:
c.index_select(dim=0,index=indices)

tensor([[30, 31, 32],
        [33, 34, 35]])

In [51]:
c.index_select(dim=1,index=indices)

tensor([[28, 29],
        [31, 32],
        [34, 35],
        [37, 38],
        [40, 41],
        [16, 17],
        [19, 20],
        [22, 23],
        [25, 26]])

In [52]:
c=c.unsqueeze(dim=0)
c.shape


torch.Size([1, 9, 3])

In [53]:
indices=torch.LongTensor([0])
c.index_select(dim=0,index=indices)

tensor([[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35],
         [36, 37, 38],
         [39, 40, 41],
         [42, 16, 17],
         [18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

In [54]:
torch.nonzero(torch.Tensor([1,1,1,0,1,0,1])) #Returns indexes 

tensor([[0],
        [1],
        [2],
        [4],
        [6]])

In [55]:
c=c.squeeze(dim=0)
c.shape

torch.Size([9, 3])

In [56]:
a,b,c=c.split(3)

In [57]:
a

tensor([[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]])

In [58]:
b

tensor([[36, 37, 38],
        [39, 40, 41],
        [42, 16, 17]])

In [59]:
c

tensor([[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]])

In [60]:
c.t() #Transpose

tensor([[18, 21, 24],
        [19, 22, 25],
        [20, 23, 26]])

In [61]:
c.transpose(dim0=0,dim1=1)

tensor([[18, 21, 24],
        [19, 22, 25],
        [20, 23, 26]])

In [62]:
c.transpose(dim0=1,dim1=0)

tensor([[18, 21, 24],
        [19, 22, 25],
        [20, 23, 26]])

In [63]:
c=c.unsqueeze(dim=0)
c.shape

torch.Size([1, 3, 3])

In [64]:
c.transpose(dim0=0,dim1=2)

tensor([[[18],
         [21],
         [24]],

        [[19],
         [22],
         [25]],

        [[20],
         [23],
         [26]]])

In [65]:
c.transpose(dim0=0,dim1=1)

tensor([[[18, 19, 20]],

        [[21, 22, 23]],

        [[24, 25, 26]]])

In [66]:
c.transpose(dim0=1,dim1=2)

tensor([[[18, 21, 24],
         [19, 22, 25],
         [20, 23, 26]]])

In [67]:
print(c.unbind(0),c.unbind(0)[0].shape)


(tensor([[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]),) torch.Size([3, 3])


In [68]:
print(c.unbind(1)) #unbind function removes a dimension from the tensor

(tensor([[18, 19, 20]]), tensor([[21, 22, 23]]), tensor([[24, 25, 26]]))


In [69]:
#Setting seed in pytorch

torch.manual_seed(42)
torch.randn(2)

tensor([0.3367, 0.1288])

In [70]:
#Verifyinga
torch.manual_seed(42)
torch.randn(2)

tensor([0.3367, 0.1288])

In [71]:
#Limiting the values of any tensor within a certain range can be done using the minimum and maximum argument
#using the clamp function. 

random_tensor=torch.arange(50,100).reshape(2,5,5)

In [72]:
torch.clamp(random_tensor,max=75,min=60)

tensor([[[60, 60, 60, 60, 60],
         [60, 60, 60, 60, 60],
         [60, 61, 62, 63, 64],
         [65, 66, 67, 68, 69],
         [70, 71, 72, 73, 74]],

        [[75, 75, 75, 75, 75],
         [75, 75, 75, 75, 75],
         [75, 75, 75, 75, 75],
         [75, 75, 75, 75, 75],
         [75, 75, 75, 75, 75]]])

In [73]:
torch.exp(torch.from_numpy(np.array([1.0])))

tensor([2.7183], dtype=torch.float64)

In [74]:
#getting only the fractional part
torch.frac(torch.exp(torch.from_numpy(np.array([1.0]))))

tensor([0.7183], dtype=torch.float64)

In [75]:
torch.log(torch.from_numpy(np.array([2.7183]))) #base here is NATURAL

tensor([1.0000], dtype=torch.float64)

In [76]:
torch.log10(torch.from_numpy(np.array([10.0])))

tensor([1.], dtype=torch.float64)

In [77]:
torch.sigmoid(torch.from_numpy(np.array([10.0*10])))

tensor([1.], dtype=torch.float64)

In [78]:
torch.sigmoid(torch.from_numpy(np.array([0.0])))

tensor([0.5000], dtype=torch.float64)