In [1]:
import numpy as np

In [ ]:
#save and load numpy objects--> .npy and .npz does that.
#If the want to store a single numpy array we can use .npy using np.save else .npz using np.savez

'''    
if 1 numpy array:
    use: .npy & np.save
else:
    use: .npz and np.savez
 '''

In [6]:
arr=np.random.random((5,4))
print(arr)

[[0.95673336 0.01517588 0.46160209 0.76077652]
 [0.43910954 0.26405395 0.75754287 0.99118461]
 [0.46980433 0.41168947 0.57936002 0.85805001]
 [0.64873152 0.55282675 0.18776832 0.67036773]
 [0.91727676 0.13106867 0.19075106 0.49419762]]


In [7]:
np.save("only_single_array.npy",arr)

In [8]:
arr_2=np.random.random((6,4))
print(arr_2)

[[0.13042913 0.5954991  0.48414924 0.84459528]
 [0.62234265 0.18517343 0.68387452 0.17726414]
 [0.25784955 0.47681821 0.11690448 0.93638542]
 [0.28702102 0.17247108 0.75482399 0.12879011]
 [0.34087291 0.17075936 0.17124153 0.75993091]
 [0.40372976 0.00272809 0.12346886 0.20546887]]


In [9]:
np.savez("multiple_arrays.npz",arr,arr_2)

In [10]:
#To load just use np.load

only_arr=np.load("only_single_array.npy")
print(only_arr)

[[0.95673336 0.01517588 0.46160209 0.76077652]
 [0.43910954 0.26405395 0.75754287 0.99118461]
 [0.46980433 0.41168947 0.57936002 0.85805001]
 [0.64873152 0.55282675 0.18776832 0.67036773]
 [0.91727676 0.13106867 0.19075106 0.49419762]]


In [14]:
arr=np.load("multiple_arrays.npz")# dictionary object

print(list(arr.keys()))


['arr_0', 'arr_1']


In [15]:
print(arr['arr_0'])

print("\n")

print(arr['arr_1'])

[[0.95673336 0.01517588 0.46160209 0.76077652]
 [0.43910954 0.26405395 0.75754287 0.99118461]
 [0.46980433 0.41168947 0.57936002 0.85805001]
 [0.64873152 0.55282675 0.18776832 0.67036773]
 [0.91727676 0.13106867 0.19075106 0.49419762]]


[[0.13042913 0.5954991  0.48414924 0.84459528]
 [0.62234265 0.18517343 0.68387452 0.17726414]
 [0.25784955 0.47681821 0.11690448 0.93638542]
 [0.28702102 0.17247108 0.75482399 0.12879011]
 [0.34087291 0.17075936 0.17124153 0.75993091]
 [0.40372976 0.00272809 0.12346886 0.20546887]]


In [17]:
# some diff methods to stack arrays


arr_1=np.random.random((3,5))
arr_2=np.random.random((2,5))

print(arr_1)
print("\n")
print(arr_2)

[[0.7823227  0.84882572 0.05435269 0.18170319 0.14498562]
 [0.56561357 0.40189983 0.15201194 0.07022896 0.04498175]
 [0.07999759 0.89046899 0.87202789 0.76046993 0.78860076]]


[[0.23271213 0.36397431 0.93424001 0.23075544 0.8985714 ]
 [0.28270002 0.54175508 0.94103832 0.97952437 0.13895486]]


In [18]:
#np.concatenate

print(np.concatenate((arr_1,arr_2),axis=0))

[[0.7823227  0.84882572 0.05435269 0.18170319 0.14498562]
 [0.56561357 0.40189983 0.15201194 0.07022896 0.04498175]
 [0.07999759 0.89046899 0.87202789 0.76046993 0.78860076]
 [0.23271213 0.36397431 0.93424001 0.23075544 0.8985714 ]
 [0.28270002 0.54175508 0.94103832 0.97952437 0.13895486]]


In [19]:
#np.r_
#remember to pass argument in list
print(np.r_[arr_1,arr_2])

[[0.7823227  0.84882572 0.05435269 0.18170319 0.14498562]
 [0.56561357 0.40189983 0.15201194 0.07022896 0.04498175]
 [0.07999759 0.89046899 0.87202789 0.76046993 0.78860076]
 [0.23271213 0.36397431 0.93424001 0.23075544 0.8985714 ]
 [0.28270002 0.54175508 0.94103832 0.97952437 0.13895486]]


In [20]:
#and there is also our fav hstack and vstack that we covered previously!!