In [1]:
import numpy as np

In [5]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

In [7]:
%timeit (a+b)

643 ns ± 4.47 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [8]:
# to check the dimensions
print(a.ndim)

1


In [14]:
#To check shape
print(a.shape)

print("\n")

#To check itemsize in bytes
print(a.itemsize)

(5,)


4


In [16]:
#To compute log,sin,exp etc of array

print(np.log(a))

print("\n")

print(np.sin(a))

print("\n")

print(np.exp(a))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [19]:
#Numpy arrays are mutable that is they can be changed

a.fill(8) #fills the array with the arg number till the length of the array

print(a)

[8 8 8 8 8]


In [23]:
mat=np.array([[1,2,3],[4,5,6]])
print(mat.size) #total elements in array
print(len(mat)) #spot the difference

6
2


In [27]:
#Updating arrays
mat[1,0]=14 #Not rec mat[1][0] will work but not rec
print(mat)

[[ 1  2  3]
 [14  5  6]]


In [30]:
#Array slicing

mat_new=np.array(
        [
        [1,2,3,4,5],
        [6,7,8,9,10],
        [11,12,13,14,15],
        [16,17,18,19,20],
        [21,22,23,24,25]
        ]
)

In [33]:
print(mat_new[0,2:4])

print("\n")

print(mat_new[:,2])

[3 4]


[ 3  8 13 18 23]


In [34]:
#strides

print(mat_new[0::3,1::3])

[[ 2  5]
 [17 20]]


In [36]:
#create an array auto

mat=np.arange(25).reshape(5,5)
print(mat)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [37]:
# to check attributes of numpy array

print(mat.flags)

print("\n")

print(mat.data)

print("\n")



  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False






In [38]:
#Boolean arrays

a=np.arange(5).reshape(5)

In [40]:
a.astype(bool)

array([False,  True,  True,  True,  True])

In [42]:
a=np.arange(10)

In [47]:

c=a<8

print(c)


c=a<8

print(c.astype(np.int32))

[ True  True  True  True  True  True  True  True False False]
[1 1 1 1 1 1 1 1 0 0]


In [49]:
print(a[c])

print(a)

print(a[a<8])

[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7]


In [50]:
#   &->and |->or ^->xor ~->not

In [51]:
a=np.arange(15)

In [52]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
print(a[(a>5) & (a<11)])

[ 6  7  8  9 10]
