In [1]:
import numpy as np

In [4]:
#Sorting

arr_1=np.random.randint(10,100,size=[20])

In [5]:
print(arr_1)

[94 11 48 17 67 78 11 51 98 44 96 82 68 70 24 49 54 72 88 28]


In [6]:
print(np.sort(arr_1))

[11 11 17 24 28 44 48 49 51 54 67 68 70 72 78 82 88 94 96 98]


In [7]:
#sorting 2-d 

arr_2=np.random.randint(10,100,size=[5,5])

In [8]:
print(arr_2)

[[77 18 40 44 44]
 [59 53 44 50 72]
 [57 13 81 53 54]
 [97 10 69 44 27]
 [59 58 79 79 66]]


In [10]:
#sorting along rows
print(np.sort(arr_2,axis=0))

print("\n")

#sorting along columns
print(np.sort(arr_2,axis=1))

[[57 10 40 44 27]
 [59 13 44 44 44]
 [59 18 69 50 54]
 [77 53 79 53 66]
 [97 58 81 79 72]]


[[18 40 44 44 77]
 [44 50 53 59 72]
 [13 53 54 57 81]
 [10 27 44 69 97]
 [58 59 66 79 79]]


In [12]:
#if we want order of indices that would make a sorted array we can use np.argsort


In [13]:
arr_1=np.random.randint(1,25,size=[15])

In [16]:
print(arr_1)
print("\n")
print(np.argsort(arr_1,axis=0)) ##these are the indices which would give sorted array

[24  9 24 12 12 13  6  2 14  3 22  6 10 21  8]


[ 7  9  6 11 14  1 12  3  4  5  8 13 10  0  2]


In [21]:
print(arr_1[[ 7,  9,  6 ,11, 14,  1, 12,  3,  4,  5,  8 ,13 ,10  ,0  ,2]])

[ 2  3  6  6  8  9 10 12 12 13 14 21 22 24 24]


In [26]:
#to sort in reverse order

arr_2=np.random.randint(1,25,size=[5])
print(arr_2)
print("\n")
res_indx=arr_2.argsort(axis=0)
print(res_indx)
print("\n")
res_indx_new=res_indx[::-1]
print(res_indx_new)
print("\n")
print("The array is ascending order is {} ".format(arr_2[res_indx]))
print("\n")
print("The array is descending order is {} ".format(arr_2[res_indx_new]))

[ 3  7 21  2 11]


[3 0 1 4 2]


[2 4 1 0 3]


The array is ascending order is [ 2  3  7 11 21] 


The array is descending order is [21 11  7  3  2] 


In [27]:
#numpy.searchsorted -->gives the index position at which a number should be inserted in order to keep the array sorted

In [49]:
arr_new=np.random.randint(1,25,size=[5])
print(arr_new)

[ 1  4  3 11 20]


In [50]:
print(np.searchsorted(arr_new,108,side='left')) 
print(np.searchsorted(arr_new,11,side='left')) 

5
3


In [60]:
#This is a much faster alternative to np.random.choice

arr_1=[2,2,4,4,4,5,6,7]
probability=np.random.random(10)
probability=probability/probability.sum()

In [88]:
probability

array([0.14352697, 0.05603694, 0.00273751, 0.15574435, 0.06352141,
       0.20626228, 0.09302262, 0.07822929, 0.07527779, 0.12564083])

In [89]:
#to add upon in the array

probability.cumsum()

array([0.14352697, 0.19956391, 0.20230143, 0.35804578, 0.42156718,
       0.62782946, 0.72085209, 0.79908137, 0.87435917, 1.        ])

In [79]:
np.random.choice(arr_1,p=[0.1,0.1,0.4,0.4,0.0,0.0,0.0,0.0])

4

In [80]:
%timeit np.random.choice(arr_1,p=[0.1,0.1,0.4,0.4,0.0,0.0,0.0,0.0])

25.8 µs ± 463 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [90]:
arr_1[np.searchsorted(probability.cumsum(),np.random.random())]

4