In [1]:
import numpy as np

In [4]:
#create a sequence of date

start=np.datetime64('2018-09-01')
end=np.datetime64('2018-10-01')

In [5]:
data=np.arange(start,end)

In [6]:
data

array(['2018-09-01', '2018-09-02', '2018-09-03', '2018-09-04',
       '2018-09-05', '2018-09-06', '2018-09-07', '2018-09-08',
       '2018-09-09', '2018-09-10', '2018-09-11', '2018-09-12',
       '2018-09-13', '2018-09-14', '2018-09-15', '2018-09-16',
       '2018-09-17', '2018-09-18', '2018-09-19', '2018-09-20',
       '2018-09-21', '2018-09-22', '2018-09-23', '2018-09-24',
       '2018-09-25', '2018-09-26', '2018-09-27', '2018-09-28',
       '2018-09-29', '2018-09-30'], dtype='datetime64[D]')

In [7]:
#to check it is a weekday or not

print(np.is_busday(data))

[False False  True  True  True  True  True False False  True  True  True
  True  True False False  True  True  True  True  True False False  True
  True  True  True  True False False]


In [8]:
#coolest feature of numpy is np.vectorize
#it can make a function that accepts scalar args to a function that can accept an array

In [9]:
def sum_from_one_to_x(arg):
    cache=list(range(1,arg))
    return sum(cache)

In [11]:
print(sum_from_one_to_x(10))

45


In [13]:
print(sum_from_one_to_x([1,2,3,4,5,6,7,8,9,10]))

TypeError: 'list' object cannot be interpreted as an integer

In [17]:
#let's do this

vec_func=np.vectorize(sum_from_one_to_x,otypes=[int])
args=np.array([1,2,3,4,5,6,7,8,9,10])

In [18]:
print(vec_func(args))

[ 0  1  3  6 10 15 21 28 36 45]


In [19]:
#np.ravel flattens an array

arr_1=np.random.random((5,2))

In [20]:
arr_1

array([[0.82566456, 0.99330003],
       [0.44939032, 0.37768314],
       [0.59600415, 0.52320272],
       [0.05551801, 0.54018224],
       [0.65035761, 0.86626866]])

In [21]:
print(np.ravel(arr_1))#order="C" flattens by columns

[0.82566456 0.99330003 0.44939032 0.37768314 0.59600415 0.52320272
 0.05551801 0.54018224 0.65035761 0.86626866]


In [24]:
print(np.ravel(arr_1,order="F"))#order="F flattens by Rows

[0.82566456 0.44939032 0.59600415 0.05551801 0.65035761 0.99330003
 0.37768314 0.52320272 0.54018224 0.86626866]


In [25]:
#np.roll--> Roll array elements along a given axis.

In [37]:
arr_new=np.arange(10).reshape(2,5)
print(arr_new)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [38]:
print(np.roll(arr_new,1,axis=None)) 

[[9 0 1 2 3]
 [4 5 6 7 8]]


In [56]:
##axis=None-- something like this  process is done in the backend 
arr=np.ravel(arr_new)
from collections import deque
d=deque(arr)
d.rotate(1)
arr=np.array(list(d)).reshape(2,5)
print(arr)


[[9 0 1 2 3]
 [4 5 6 7 8]]


In [57]:
print(np.roll(arr_new,1,axis=0)) 

[[5 6 7 8 9]
 [0 1 2 3 4]]


In [58]:
print(np.roll(arr_new,1,axis=1)) 

[[4 0 1 2 3]
 [9 5 6 7 8]]


In [59]:
#apply afunction column or row wise -->np.apply_along_axis

In [60]:
arr=np.random.randint(1,25,size=[2,5])

In [61]:
arr

array([[ 8, 23,  2, 11,  8],
       [11,  8,  7, 18, 11]])

In [62]:
def function(arg):
    
    return np.max(arg)-np.min(arg)

In [64]:
print(np.apply_along_axis(function,axis=0,arr=arr))

[ 3 15  5  7  3]


In [65]:
print(np.apply_along_axis(function,axis=1,arr=arr))

[21 11]


In [67]:
#to insert a new dimension to your array-->np.newaxis

In [76]:
arr_new=arr_new.ravel()
print(arr_new)
print(arr_new.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [74]:
print(arr_new[np.newaxis,:].shape)#row axis is added


(1, 10)


In [75]:
print(arr_new[:,np.newaxis].shape)#column axis 

(10, 1)


In [77]:
#clip -->as the name suggest suppressing the num between high and low

In [78]:
arr_new

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
arr_new.clip(0,5)

array([0, 1, 2, 3, 4, 5, 5, 5, 5, 5])

In [84]:
#To allot bins return the index position of the bin the element belong to-->np.digitize

In [85]:
arr_new

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
bins=np.array([2,4,6,8])

In [87]:
print(np.digitize(arr_new,bins))

[0 0 1 1 2 2 3 3 4 4]
