In [1]:
import numpy as np

In [2]:
#dot product

a=np.array([2,4,6])
b=np.array([1,3,5])
print(a.dot(b)) #2*1+4*3+6*5 length of a  projected on b with 1-d matrix it does inner product but matrix mul in 2d

44


In [6]:
#norm of the vectors i.e the length of the vectors
print(np.linalg.norm(a),np.linalg.norm(b))

7.483314773547883 5.916079783099616


In [8]:
#unit vectors

print(b/np.linalg.norm(b)) #unit vectors of  b

[0.16903085 0.50709255 0.84515425]


In [16]:
a=np.random.randint(10,100,size=(3,3))

In [26]:
#to solve ax=b i.e x=a. i.e x => inv(a)*b we use np.linalg.solve

In [27]:
np.linalg.inv(a) #inverse of a matrix

array([[ 0.02797959, -0.0160268 , -0.00909701],
       [-0.0101122 ,  0.0187281 , -0.00286461],
       [-0.01606211,  0.00399456,  0.01989336]])

In [28]:
a

array([[87, 64, 49],
       [56, 93, 39],
       [59, 33, 82]])

In [29]:
b=np.random.randint(10,15,size=[3,2])

In [30]:
np.linalg.solve(a,b)

array([[0.06510474, 0.08737277],
       [0.06465453, 0.04303975],
       [0.08567343, 0.05395969]])

In [32]:
a=np.eye(3)

In [33]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
#determinent
print(np.linalg.det(a))

1.0


In [37]:
#transpose a matrix
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [38]:
print(a.T)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [39]:
a=np.random.randint(1,15,size=[2,2])
b=np.random.randint(1,15,size=[2,2])

In [40]:
a

array([[11,  7],
       [10,  6]])

In [41]:
b

array([[ 5, 13],
       [ 2, 11]])

In [58]:
print(np.dot(a,b)) # 11*5+7*2=69,11*13+7*11=220,10*5+6*2=62,10*13+6*11=196 remember now it does matrix mul

[[ 69 220]
 [ 62 196]]


In [60]:
print(a*b)#element wise multiplication

[[55 91]
 [20 66]]


In [61]:
np.matmul(a,b)

array([[ 69, 220],
       [ 62, 196]])

In [45]:
#to make a matrix

In [53]:
arr=np.mat("1 5 3;4 5 6;7 8 9")

In [54]:
print(arr,type(arr))

[[1 5 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.matrixlib.defmatrix.matrix'>


In [56]:
arr.I #this inverse will only work with matrix type else use inv

matrix([[-0.16666667, -1.16666667,  0.83333333],
        [ 0.33333333, -0.66666667,  0.33333333],
        [-0.16666667,  1.5       , -0.83333333]])

In [62]:
np.inner(a,b)

array([[146,  99],
       [128,  86]])

In [73]:
diag=np.diag([3,5,7,11])#creates diagonal matrix
print(diag)

[[ 3  0  0  0]
 [ 0  5  0  0]
 [ 0  0  7  0]
 [ 0  0  0 11]]


In [85]:
#eigen values

print(np.linalg.eigvals(diag))

[ 3.  5.  7. 11.]


In [87]:
print(np.linalg.eig(diag)) #eigen vectors

(array([ 3.,  5.,  7., 11.]), array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]))


In [92]:
np.tensordot(a,b,axes=2) #inner product 55+91+20+66=232

array(232)

In [97]:
np.tensordot(a,b,axes=1)# -->matrix multiplication

array([[ 69, 220],
       [ 62, 196]])

In [102]:
np.tensordot(a,b,axes=0) # takes one elment from the first matrix and does  scalar multiplication on the other

array([[[[ 55, 143],
         [ 22, 121]],

        [[ 35,  91],
         [ 14,  77]]],


       [[[ 50, 130],
         [ 20, 110]],

        [[ 30,  78],
         [ 12,  66]]]])

In [104]:
a=np.random.randint(1,7,size=(3,4))
a

array([[1, 5, 1, 4],
       [5, 6, 1, 2],
       [1, 1, 1, 3]])

In [111]:
b=np.random.randint(1,7,size=(3,4))
b

array([[2, 5, 2, 5],
       [5, 1, 3, 4],
       [3, 1, 2, 3]])

In [112]:
np.tensordot(a,b,axes=2)

array(106)

In [114]:
np.tensordot(a,b,axes=0)

array([[[[ 2,  5,  2,  5],
         [ 5,  1,  3,  4],
         [ 3,  1,  2,  3]],

        [[10, 25, 10, 25],
         [25,  5, 15, 20],
         [15,  5, 10, 15]],

        [[ 2,  5,  2,  5],
         [ 5,  1,  3,  4],
         [ 3,  1,  2,  3]],

        [[ 8, 20,  8, 20],
         [20,  4, 12, 16],
         [12,  4,  8, 12]]],


       [[[10, 25, 10, 25],
         [25,  5, 15, 20],
         [15,  5, 10, 15]],

        [[12, 30, 12, 30],
         [30,  6, 18, 24],
         [18,  6, 12, 18]],

        [[ 2,  5,  2,  5],
         [ 5,  1,  3,  4],
         [ 3,  1,  2,  3]],

        [[ 4, 10,  4, 10],
         [10,  2,  6,  8],
         [ 6,  2,  4,  6]]],


       [[[ 2,  5,  2,  5],
         [ 5,  1,  3,  4],
         [ 3,  1,  2,  3]],

        [[ 2,  5,  2,  5],
         [ 5,  1,  3,  4],
         [ 3,  1,  2,  3]],

        [[ 2,  5,  2,  5],
         [ 5,  1,  3,  4],
         [ 3,  1,  2,  3]],

        [[ 6, 15,  6, 15],
         [15,  3,  9, 12],
         [ 9,  3,  6,  9]]]])

In [115]:
b=np.random.randint(1,7,size=(4,4))
np.tensordot(a,b,axes=1)

array([[21, 33, 63, 42],
       [26, 50, 69, 46],
       [15, 18, 33, 22]])