In [1]:
import numpy as np

In [5]:
#to get index position of items when conditional expression is true

arr=np.random.random(10)
print(arr)

[0.72954683 0.60571078 0.4599983  0.88923329 0.96489661 0.43225324
 0.69170595 0.69074117 0.12703844 0.9356857 ]


In [6]:
index_getter=np.where(arr>0.5)

In [7]:
print(index_getter)

(array([0, 1, 3, 4, 6, 7, 9], dtype=int64),)


In [13]:
#previously we used to get the items itself
#ex:

item_getter=arr[arr>0.5]
print(item_getter)
print("\n")
res=[]
for i in list(item_getter):
    res.append(list(arr).index(i))
print(res)

#Very redundant method but wanted to show how it would have worked in backend but this need to be more optimized

[0.72954683 0.60571078 0.88923329 0.96489661 0.69170595 0.69074117
 0.9356857 ]


[0, 1, 3, 4, 6, 7, 9]


In [17]:
#from index we can get the values using take method

print(arr.take(index_getter))

print("\n")

#or just do simple stuff 

print(arr[index_getter]) #simplicity 

[[0.72954683 0.60571078 0.88923329 0.96489661 0.69170595 0.69074117
  0.9356857 ]]


[0.72954683 0.60571078 0.88923329 0.96489661 0.69170595 0.69074117
 0.9356857 ]


In [19]:
#now what if you want to set a particular value when conditional evaluates to true or false
#np.where does this

print(np.where(arr>0.5,"Prakhar","T"))#Beautiful

['Prakhar' 'Prakhar' 'T' 'Prakhar' 'Prakhar' 'T' 'Prakhar' 'Prakhar' 'T'
 'Prakhar']


In [23]:
#to find index of man and min value in array use ->np.argmax

new_arr=np.arange(10,100,10)
print(new_arr)

[10 20 30 40 50 60 70 80 90]


In [24]:
print(np.argmax(new_arr))

8


In [34]:
#lets do this in matrix

new_arr=np.array([np.random.randint(10,100) for i in range(15)]).reshape(3,5) #complicating stuff
print(new_arr)

[[45 28 91 56 67]
 [46 89 82 49 77]
 [46 69 83 15 74]]


In [38]:
#lets find across rows,shall we?
#Returns the indices of the maximum values along an axis
print(np.argmax(new_arr,axis=1))#columns
print("\n")
print(np.argmax(new_arr,axis=0))#rows

[2 1 2]


[1 1 0 0 1]


In [39]:
#Import data from a csv file in numpy


In [40]:
#use either np.loadtxt or np.genfromtxt(better one@!)

In [41]:
#To turn off scientific notation 
np.set_printoptions(suppress=False)

In [54]:
#Import the data 
data=np.genfromtxt("https://bit.ly/2LLYxJE",delimiter=",",skip_header=1,filling_values=-999,dtype=float)

In [55]:
data

array([[  18.,    8.,  307., ...,   70.,    1., -999.],
       [  15.,    8.,  350., ...,   70.,    1., -999.],
       [  18.,    8.,  318., ...,   70.,    1., -999.],
       ...,
       [  32.,    4.,  135., ...,   82.,    1., -999.],
       [  28.,    4.,  120., ...,   82.,    1., -999.],
       [  31.,    4.,  119., ...,   82.,    1., -999.]])

In [56]:
#to save it to csv
np.savetxt("out.csv",data,delimiter=",")