In [1]:

import numpy as np
arr_1=np.arange(16).reshape(2,8)
arr_2=np.arange(32).reshape(4,8)





In [10]:
#vstack -> vertically stacking arrays 
print(arr_1)
print("\n")
print(arr_2)
print("\n")
print(np.vstack((arr_1,arr_2)))
print("\n")
print(np.vstack((arr_1,arr_2)).shape)
print("\n")
print(np.hstack((arr_1,arr_2[:2,])))
print("\n")
print(np.hstack((arr_1,arr_2[:2,])).shape)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]


[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]


(6, 8)


[[ 0  1  2  3  4  5  6  7  0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15  8  9 10 11 12 13 14 15]]


(2, 16)


In [13]:
#to generate random numnbers

np.random.random(3) # Hi numpy! please give me  three random numbers

array([0.0657933, 0.2167375, 0.7517481])

In [15]:
# to generate matrix

np.random.random((2,5))

array([[0.73266369, 0.18934403, 0.90752089, 0.04452556, 0.43979561],
       [0.92360644, 0.10610171, 0.23176915, 0.67207403, 0.97952923]])

In [17]:
#to generate an integer

np.random.randint(low=15,high=100,)

48

In [23]:
#some other random
np.random.rand(5,3)



array([[0.7516845 , 0.57788576, 0.65971936],
       [0.53276823, 0.82909056, 0.08047597],
       [0.8648645 , 0.20171328, 0.1524401 ],
       [0.10521582, 0.38204951, 0.35592064],
       [0.05441586, 0.7533078 , 0.38484883]])

In [25]:
np.random.randn(3,5)#Normal dist

array([[ 0.06520609,  1.22530097,  1.6174446 ,  1.03242068, -0.55763759],
       [-1.50625648, -0.30204897,  0.29441791, -0.62083706, -0.38657149],
       [-0.80487228,  1.45881707,  0.72662847, -1.11118562, -0.95200287]])

In [32]:
arr=np.random.random((6,4))

In [33]:
arr

array([[0.91389769, 0.02874349, 0.37004405, 0.45265882],
       [0.74578483, 0.60293568, 0.55129194, 0.90362628],
       [0.27850081, 0.20523371, 0.29995966, 0.6469996 ],
       [0.77332249, 0.86784281, 0.13228109, 0.51087582],
       [0.83071826, 0.56229467, 0.57719787, 0.70192568],
       [0.27648127, 0.35438253, 0.22692741, 0.70640969]])

In [35]:
#split this array
a,b=(np.hsplit(arr,2))

In [36]:
a


array([[0.91389769, 0.02874349],
       [0.74578483, 0.60293568],
       [0.27850081, 0.20523371],
       [0.77332249, 0.86784281],
       [0.83071826, 0.56229467],
       [0.27648127, 0.35438253]])

In [37]:
b

array([[0.37004405, 0.45265882],
       [0.55129194, 0.90362628],
       [0.29995966, 0.6469996 ],
       [0.13228109, 0.51087582],
       [0.57719787, 0.70192568],
       [0.22692741, 0.70640969]])